include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    always_declare_return_types: true
    sort_pub_dependencies: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_single_quotes: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    todo: ignore