name: multitests
description: A platform created by 2.5 Perceivers and Adorkw to simplify the online tests, give them a nice and a simple interface, with amazing interpretations, colors and icons

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.1+22

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animations: ^2.0.7
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.5.2
  flutter:
    sdk: flutter
  go_router: ^5.1.10
  provider: ^6.0.4
  share_plus_dialog:
    git: https://github.com/2-5-perceivers/share_plus_dialog.git
    version: ^1.1.1
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MultiIcons
      fonts:
        - asset: fonts/MultiIcons.ttf
