name: multitests
description: A platform for testing your maturity, personality and many more

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  animations: ^2.0.3
  dynamic_color: ^1.5.2
  flutter:
    sdk: flutter
  go_router: ^4.2.7
  provider: ^6.0.3
  share_plus_dialog:
    git: https://github.com/2-5-perceivers/share_plus_dialog.git
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: MultiIcons
      fonts:
        - asset: fonts/MultiIcons.ttf
