/// Flutter icons MultiIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MultiIcons
///      fonts:
///       - asset: fonts/MultiIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MultiIcons {
  MultiIcons._();

  static const _kFontFam = 'MultiIcons';
  static const String? _kFontPkg = null;

  static const IconData nonScience =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
